# syntax=docker/dockerfile:1.7

ARG DOTNET_SDK_IMAGE=mcr.microsoft.com/dotnet/sdk:10.0
ARG DOTNET_RUNTIME_IMAGE=mcr.microsoft.com/dotnet/aspnet:10.0
ARG BUILD_CONFIGURATION=Release

# ---------------------------------------------------------------------------
# sdk-base: shared SDK environment
# ---------------------------------------------------------------------------
FROM ${DOTNET_SDK_IMAGE} AS sdk-base
ENV DOTNET_NOLOGO=true \
    DOTNET_CLI_TELEMETRY_OPTOUT=true \
    DOTNET_GENERATE_ASPNETCORE_CERTIFICATE=false \
    NUGET_XMLDOC_MODE=skip
WORKDIR /src

# ---------------------------------------------------------------------------
# restore: dotnet restore against central package management.
# --locked-mode reads packages.lock.json (one per project, generated by
# Directory.Build.props's RestorePackagesWithLockFile=true) and fails the
# restore if a transitive's content hash drifts from what was committed
# — supply-chain defence for the native bindings introduced by RM-M2-OP-05.
# Bumping a package version requires the developer to run
# `dotnet restore /p:ForceEvaluate=true` locally and commit the refreshed
# lock files alongside the Directory.Packages.props change.
# ---------------------------------------------------------------------------
FROM sdk-base AS restore
COPY global.json Directory.Build.props Directory.Packages.props .editorconfig ./
COPY BatteryEms.sln ./
COPY src/ src/
COPY tests/ tests/
COPY config/ config/
RUN dotnet restore BatteryEms.sln --locked-mode

# ---------------------------------------------------------------------------
# lint: dotnet build -warnaserror (RM-M1-01, RM-M1-21)
# ---------------------------------------------------------------------------
FROM restore AS lint
ARG BUILD_CONFIGURATION
RUN dotnet build BatteryEms.sln \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-restore \
    -warnaserror

# ---------------------------------------------------------------------------
# arch-check: boundary tests (RM-M1-22, RM-M1-23)
# ---------------------------------------------------------------------------
FROM lint AS arch-check
ARG BUILD_CONFIGURATION
RUN dotnet test tests/BatteryEms.ArchitectureTests/BatteryEms.ArchitectureTests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal"

# ---------------------------------------------------------------------------
# test: domain + application unit tests (RM-M1-02/03/04/05/06/07/08)
# ---------------------------------------------------------------------------
FROM lint AS test
ARG BUILD_CONFIGURATION
RUN dotnet test tests/hexagon/BatteryEms.Domain.Tests/BatteryEms.Domain.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal" \
 && dotnet test tests/hexagon/BatteryEms.Application.Tests/BatteryEms.Application.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal" \
 && dotnet test tests/infrastructure/BatteryEms.Infrastructure.Tests/BatteryEms.Infrastructure.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal" \
 && dotnet test tests/adapters/driven/BatteryEms.Adapters.Modbus.Tests/BatteryEms.Adapters.Modbus.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal" \
 && dotnet test tests/adapters/driven/BatteryEms.Adapters.Mqtt.Tests/BatteryEms.Adapters.Mqtt.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal" \
 && dotnet test tests/adapters/driven/BatteryEms.Adapters.Telemetry.Tests/BatteryEms.Adapters.Telemetry.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal" \
 && dotnet test tests/adapters/driven/BatteryEms.Adapters.Optimization.Tests/BatteryEms.Adapters.Optimization.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal" \
 && dotnet test tests/adapters/driven/BatteryEms.Adapters.Persistence.Tests/BatteryEms.Adapters.Persistence.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal" \
 && dotnet test tests/adapters/driven/BatteryEms.Adapters.NativeInterop.Tests/BatteryEms.Adapters.NativeInterop.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal" \
 && dotnet test tests/adapters/driving/BatteryEms.Worker.Tests/BatteryEms.Worker.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal" \
 && dotnet test tests/adapters/driving/BatteryEms.Api.Tests/BatteryEms.Api.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --logger "console;verbosity=normal"

# ---------------------------------------------------------------------------
# test-safety: safety-path tests filtered by trait Category=Safety (RM-M1-07)
# ---------------------------------------------------------------------------
FROM lint AS test-safety
ARG BUILD_CONFIGURATION
RUN dotnet test tests/hexagon/BatteryEms.Domain.Tests/BatteryEms.Domain.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --filter "Category=Safety" \
    --logger "console;verbosity=normal" \
 && dotnet test tests/hexagon/BatteryEms.Application.Tests/BatteryEms.Application.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --filter "Category=Safety" \
    --logger "console;verbosity=normal"

# ---------------------------------------------------------------------------
# coverage-gate: line coverage threshold for M1 production assemblies (RM-M1-20)
# Threshold 90% per project (Domain; Application + Optimization adapter).
# Adapter skeletons (Modbus/MQTT/Persistence/Telemetry/Worker/Api/Infrastructure)
# stay outside the gate until they carry production code.
# ---------------------------------------------------------------------------
FROM lint AS coverage-gate
ARG BUILD_CONFIGURATION
# ExcludeByFile drops Microsoft.AspNetCore.OpenApi-generated source files
# (and any other source-generator output) from the report so the OpenApi
# transformer types — which the source generator emits into every project
# transitively reaching the Api package via central package pinning —
# don't drag the percentage down. The generated file convention is
# Roslyn-standard `obj/.../*.generated.cs`.
RUN dotnet test tests/hexagon/BatteryEms.Domain.Tests/BatteryEms.Domain.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-restore \
    /p:CollectCoverage=true \
    /p:CoverletOutputFormat=cobertura \
    /p:CoverletOutput=/src/coverage/Domain/ \
    /p:Include="[BatteryEms.Domain]*" \
    /p:ExcludeByFile="**/*.generated.cs" \
    /p:Threshold=90 \
    /p:ThresholdType=line \
    /p:ThresholdStat=total \
 && dotnet test tests/hexagon/BatteryEms.Application.Tests/BatteryEms.Application.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-restore \
    /p:CollectCoverage=true \
    /p:CoverletOutputFormat=cobertura \
    /p:CoverletOutput=/src/coverage/Application/ \
    /p:Include="[BatteryEms.Application]*" \
    /p:ExcludeByFile="**/*.generated.cs" \
    /p:Threshold=90 \
    /p:ThresholdType=line \
    /p:ThresholdStat=total \
 && dotnet test tests/adapters/driven/BatteryEms.Adapters.Optimization.Tests/BatteryEms.Adapters.Optimization.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-restore \
    /p:CollectCoverage=true \
    /p:CoverletOutputFormat=cobertura \
    /p:CoverletOutput=/src/coverage/Optimization/ \
    /p:Include="[BatteryEms.Adapters.Optimization]*" \
    /p:ExcludeByFile="**/*.generated.cs" \
    /p:Threshold=90 \
    /p:ThresholdType=line \
    /p:ThresholdStat=total \
 && dotnet test tests/infrastructure/BatteryEms.Infrastructure.Tests/BatteryEms.Infrastructure.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-restore \
    /p:CollectCoverage=true \
    /p:CoverletOutputFormat=cobertura \
    /p:CoverletOutput=/src/coverage/Infrastructure/ \
    /p:Include="[BatteryEms.Infrastructure]*" \
    /p:ExcludeByFile="**/*.generated.cs" \
    /p:Threshold=90 \
    /p:ThresholdType=line \
    /p:ThresholdStat=total \
 && dotnet test tests/adapters/driven/BatteryEms.Adapters.Modbus.Tests/BatteryEms.Adapters.Modbus.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-restore \
    /p:CollectCoverage=true \
    /p:CoverletOutputFormat=cobertura \
    /p:CoverletOutput=/src/coverage/Modbus/ \
    /p:Include="[BatteryEms.Adapters.Modbus]*" \
    /p:Exclude="[BatteryEms.Adapters.Modbus]*.FluentModbusClient" \
    /p:ExcludeByFile="**/*.generated.cs" \
    /p:Threshold=90 \
    /p:ThresholdType=line \
    /p:ThresholdStat=total \
 && dotnet test tests/adapters/driven/BatteryEms.Adapters.Telemetry.Tests/BatteryEms.Adapters.Telemetry.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-restore \
    /p:CollectCoverage=true \
    /p:CoverletOutputFormat=cobertura \
    /p:CoverletOutput=/src/coverage/Telemetry/ \
    /p:Include="[BatteryEms.Adapters.Telemetry]*" \
    /p:ExcludeByFile="**/*.generated.cs" \
    /p:Threshold=90 \
    /p:ThresholdType=line \
    /p:ThresholdStat=total \
 && dotnet test tests/adapters/driving/BatteryEms.Worker.Tests/BatteryEms.Worker.Tests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-restore \
    /p:CollectCoverage=true \
    /p:CoverletOutputFormat=cobertura \
    /p:CoverletOutput=/src/coverage/Worker/ \
    /p:Include="[BatteryEms.Worker]*" \
    /p:ExcludeByFile="**/*.generated.cs" \
    /p:Threshold=90 \
    /p:ThresholdType=line \
    /p:ThresholdStat=total

# ---------------------------------------------------------------------------
# publish: produces self-contained framework-dependent output for the host
# composition root. Trim is OFF for M1 — Dapper, Npgsql and the OpenAPI
# source generator all reflect on types that trimming would strip.
# (LH-DEPLOY-001 + LH-DEPLOY-003)
# ---------------------------------------------------------------------------
FROM lint AS publish
ARG BUILD_CONFIGURATION
RUN dotnet publish src/host/BatteryEms.Host/BatteryEms.Host.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-restore \
    --output /publish

# ---------------------------------------------------------------------------
# native-build (RM-M3-06 part 1): Build + smoke-test the native
# control core. The runtime stage below COPYs the built .so into
# /app/native/ (RM-M3-06 part 2), so this stage MUST be defined
# before runtime — the BuildKit graph rejects forward references.
# `make native-build` exercises just this stage; the .so is also
# consumed by `test-native-interop` (RM-M3-07) and `runtime`.
#
# Base choice: the .NET SDK image, NOT a vanilla Debian slim. Two
# reasons.
#   1. ABI alignment. The runtime image (mcr.microsoft.com/dotnet/
#      aspnet:10.0) is Ubuntu 24.04 LTS (Noble, glibc 2.39); a .so
#      built on a newer-glibc base (e.g. debian:trixie-slim,
#      glibc 2.41) is forward-incompatible and breaks the dynamic
#      linker on Noble the moment a stdlib symbol from glibc 2.40+
#      appears. Building on the SDK image — same Noble base as the
#      runtime — guarantees ABI compatibility by construction.
#   2. CVE hygiene. Microsoft patches dotnet/sdk:10.0 on the same
#      cadence as dotnet/aspnet:10.0; pinning to a frozen Debian
#      base would silently accumulate vulnerabilities (no scanner
#      gate yet, so the drift would not surface).
# build-essential + cmake are the only extras the SDK image lacks
# for the C++ build.
# ---------------------------------------------------------------------------
FROM ${DOTNET_SDK_IMAGE} AS native-build
RUN apt-get update \
 && apt-get install --yes --no-install-recommends \
        build-essential \
        cmake \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /src
COPY native/battery_control_core/ native/battery_control_core/
RUN cmake -S native/battery_control_core -B /build/native \
        -DCMAKE_BUILD_TYPE=Release \
 && cmake --build /build/native --parallel \
 && ctest --test-dir /build/native --output-on-failure

# ---------------------------------------------------------------------------
# runtime: minimal aspnet-only image, non-root user, port 8080,
# Container HEALTHCHECK against /health (LH-DEPLOY-001/002, LH-NF-004).
# ---------------------------------------------------------------------------
FROM ${DOTNET_RUNTIME_IMAGE} AS runtime
ENV DOTNET_NOLOGO=true \
    DOTNET_CLI_TELEMETRY_OPTOUT=true \
    DOTNET_GENERATE_ASPNETCORE_CERTIFICATE=false \
    ASPNETCORE_URLS=http://0.0.0.0:8080 \
    ASPNETCORE_ENVIRONMENT=Production
WORKDIR /app
# curl is needed for the container HEALTHCHECK; aspnet:10.0 ships a
# slim Debian base without it.
RUN apt-get update \
 && apt-get install --yes --no-install-recommends curl \
 && rm -rf /var/lib/apt/lists/*
COPY --from=publish --chown=app:app /publish /app
COPY --chown=app:app config/ /app/config/
# RM-M3-06 part 2: drop the native control library at the path the
# host's NativeControlOptions.LibraryPath default
# (/app/native/libbattery_control_core.so) expects. The .so is built
# in the `native-build` stage on the .NET SDK image, which shares
# the Ubuntu 24.04 (Noble) base of dotnet/aspnet:10.0 — ABI is
# aligned by construction (see the native-build stage rationale).
# NativeControl remains opt-in (Enabled=false default); the
# production routing activation is M3-D2's scope. The build-time
# ldd check below fails the image build if a future PID/state slice
# introduces an unresolved transitive dependency the runtime image
# does not ship.
COPY --from=native-build --chown=app:app /build/native/libbattery_control_core.so /app/native/libbattery_control_core.so
RUN ldd /app/native/libbattery_control_core.so > /tmp/ldd-out 2>&1 \
 && if grep -q "not found" /tmp/ldd-out; then \
        echo "[runtime] native control library has unresolved dependencies:" >&2; \
        cat /tmp/ldd-out >&2; \
        exit 1; \
    fi \
 && rm /tmp/ldd-out
# Non-root runtime: aspnet:10.0 already ships an "app" user (UID 1654)
# precisely for this purpose; reusing it keeps the image small and
# avoids fighting the base image's reserved UIDs.
USER app:app
EXPOSE 8080
HEALTHCHECK --interval=10s --timeout=3s --start-period=15s --retries=5 \
    CMD curl --fail --silent --show-error http://localhost:8080/health || exit 1
ENTRYPOINT ["dotnet", "BatteryEms.Host.dll"]

# ---------------------------------------------------------------------------
# test-native-interop (RM-M3-07): drives the layout / ABI handshake
# / non-finite-input contract subset of
# BatteryEms.NativeInterop.IntegrationTests against the real
# libbattery_control_core.so produced by the native-build stage.
# The .so is COPYed into a known path and the tests locate it via
# BESS_NATIVE_LIB_PATH (same discovery hook used on a developer
# workstation).
#
# RM-M3-11 split: parity tests are filtered OUT here (Category!=Parity)
# and run via the separate test-native-parity stage instead — that
# way each gate's failure attributes cleanly to its category and
# `gates` / `ci` can list both names.
# ---------------------------------------------------------------------------
FROM lint AS test-native-interop
ARG BUILD_CONFIGURATION
COPY --from=native-build /build/native/libbattery_control_core.so /native/libbattery_control_core.so
ENV BESS_NATIVE_LIB_PATH=/native/libbattery_control_core.so
RUN dotnet test tests/integration/BatteryEms.NativeInterop.IntegrationTests/BatteryEms.NativeInterop.IntegrationTests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --filter "Category!=Parity" \
    --logger "console;verbosity=normal"

# ---------------------------------------------------------------------------
# test-native-parity (RM-M3-10): runs the replay-based native↔.NET
# parity gate. Same project + same .so as test-native-interop, but
# filtered to the [Trait("Category", "Parity")] subset which loads
# tests/fixtures/native_parity/cases.v1.json and asserts native and
# managed kernels agree on every documented case.
# ---------------------------------------------------------------------------
FROM lint AS test-native-parity
ARG BUILD_CONFIGURATION
COPY --from=native-build /build/native/libbattery_control_core.so /native/libbattery_control_core.so
ENV BESS_NATIVE_LIB_PATH=/native/libbattery_control_core.so
RUN dotnet test tests/integration/BatteryEms.NativeInterop.IntegrationTests/BatteryEms.NativeInterop.IntegrationTests.csproj \
    --configuration "${BUILD_CONFIGURATION}" \
    --no-build \
    --no-restore \
    --filter "Category=Parity" \
    --logger "console;verbosity=normal"

# ---------------------------------------------------------------------------
# native-lint (RM-M3-09): clang-tidy against the native control core
# using the project's `.clang-tidy` config. CMAKE_EXPORT_COMPILE_COMMANDS
# emits the compile_commands.json clang-tidy needs to see the same
# -Werror / -W* flags the production build uses. The gate fails on any
# finding (`--warnings-as-errors=*`); FetchContent sources are filtered
# out via HeaderFilterRegex in `.clang-tidy`. clang-tidy is pulled from
# the same Ubuntu Noble base the runtime image uses.
# ---------------------------------------------------------------------------
FROM ${DOTNET_SDK_IMAGE} AS native-lint
RUN apt-get update \
 && apt-get install --yes --no-install-recommends \
        build-essential \
        cmake \
        clang-tidy \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /src
COPY native/battery_control_core/ native/battery_control_core/
RUN cmake -S native/battery_control_core -B /build/native-lint \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
 && clang-tidy \
        -p /build/native-lint \
        --warnings-as-errors=* \
        native/battery_control_core/src/compute.c

# ---------------------------------------------------------------------------
# native-sanitizer (RM-M3-09): rebuild the .so + test binary with
# AddressSanitizer + UndefinedBehaviorSanitizer instrumentation and
# run the doctest suite under -fno-sanitize-recover=all. Hits any
# undefined behaviour, use-after-free, heap/stack overflows, or
# misaligned pointer dereferences that the value-only kernel might
# acquire as the surface grows (PID state in RM-M3-13 most notably).
# ---------------------------------------------------------------------------
FROM ${DOTNET_SDK_IMAGE} AS native-sanitizer
RUN apt-get update \
 && apt-get install --yes --no-install-recommends \
        build-essential \
        cmake \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /src
COPY native/battery_control_core/ native/battery_control_core/
RUN cmake -S native/battery_control_core -B /build/native-san \
        -DCMAKE_BUILD_TYPE=Debug \
        -DBCC_ENABLE_SANITIZERS=ON \
 && cmake --build /build/native-san --parallel \
 && ctest --test-dir /build/native-san --output-on-failure

# ---------------------------------------------------------------------------
# native-coverage (RM-M3-09): instrumented build + gcovr report.
# CMAKE_BUILD_TYPE=Debug + BCC_ENABLE_COVERAGE=ON adds --coverage to
# both compile and link steps so .gcno / .gcda files land alongside
# the object code. After ctest runs, gcovr aggregates the .gcda data,
# filtering to the production source tree and excluding the
# FetchContent _deps directory (doctest is test infrastructure, not
# production code under coverage). The TOTAL line is extracted into
# summary.txt for the threshold check stage to parse.
# ---------------------------------------------------------------------------
FROM ${DOTNET_SDK_IMAGE} AS native-coverage
RUN apt-get update \
 && apt-get install --yes --no-install-recommends \
        build-essential \
        cmake \
        gcovr \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /src
COPY native/battery_control_core/ native/battery_control_core/
RUN cmake -S native/battery_control_core -B /build/native-cov \
        -DCMAKE_BUILD_TYPE=Debug \
        -DBCC_ENABLE_COVERAGE=ON \
 && cmake --build /build/native-cov --parallel \
 && ctest --test-dir /build/native-cov --output-on-failure \
 && mkdir -p /build/native-cov/coverage \
 && gcovr \
        --root /src/native/battery_control_core \
        --filter /src/native/battery_control_core/src \
        --object-directory /build/native-cov \
        --exclude /build/native-cov/_deps \
        > /build/native-cov/coverage/coverage.txt \
 && grep '^TOTAL' /build/native-cov/coverage/coverage.txt \
        > /build/native-cov/coverage/summary.txt
RUN printf '%s\n' \
    '#!/usr/bin/env sh' \
    'set -eu' \
    'printf "==> /build/native-cov/coverage/summary.txt <==\n"' \
    'cat /build/native-cov/coverage/summary.txt' \
    'printf "\n==> /build/native-cov/coverage/coverage.txt <==\n"' \
    'cat /build/native-cov/coverage/coverage.txt' \
    > /usr/local/bin/show-native-coverage \
 && chmod +x /usr/local/bin/show-native-coverage
ENTRYPOINT ["/usr/local/bin/show-native-coverage"]

# ---------------------------------------------------------------------------
# native-coverage-gate (RM-M3-09): threshold check on top of the
# coverage report. The threshold is parameterised so a future slice
# can lower it briefly during a refactor — RM-M3-09 demands 100 %
# line coverage on src/, which is the default. Anything below
# triggers a non-zero exit and breaks `make native-coverage-gate`.
# ---------------------------------------------------------------------------
FROM native-coverage AS native-coverage-gate
ARG BCC_COVERAGE_THRESHOLD=100
RUN coverage_percent="$(awk '$1 == "TOTAL" { gsub("%", "", $4); print $4 }' /build/native-cov/coverage/summary.txt)" \
 && test -n "${coverage_percent}" \
 && echo "[native-coverage-gate] line coverage: ${coverage_percent}% (threshold: ${BCC_COVERAGE_THRESHOLD}%)" >&2 \
 && if [ "${coverage_percent}" -lt "${BCC_COVERAGE_THRESHOLD}" ]; then \
        echo "error: native coverage below threshold: ${coverage_percent}% < ${BCC_COVERAGE_THRESHOLD}%" >&2; \
        exit 1; \
    fi

# ---------------------------------------------------------------------------
# Future stages (activated in later waves):
#   FROM lint AS test-integration -> Welle 3: modbus/mqtt/postgres integration
# ---------------------------------------------------------------------------
