-- Generated by d-migrate 0.9.6
-- Source: neutral schema v1.0.0 "bess-ems"
-- Target: postgresql | Generated: <stripped — see Makefile schema-generate>

CREATE TABLE "audit_events" (
    "action" TEXT NOT NULL,
    "id" BIGSERIAL,
    "operator_id" TEXT NOT NULL,
    "outcome" TEXT NOT NULL,
    "reason" TEXT NOT NULL,
    "recorded_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "target_asset_id" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE "commands" (
    "active_power_kw" DOUBLE PRECISION NOT NULL,
    "asset_id" TEXT NOT NULL,
    "command_id" TEXT NOT NULL,
    "dispatch_reason" TEXT NOT NULL,
    "dispatch_success" BOOLEAN NOT NULL,
    "dispatched_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "issued_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "mode" TEXT NOT NULL,
    "reactive_power_kvar" DOUBLE PRECISION,
    "reason" TEXT NOT NULL,
    "source" TEXT NOT NULL,
    "valid_until" TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY ("command_id")
);

CREATE TABLE "optimization_runs" (
    "asset_id" TEXT NOT NULL,
    "constraint_violations_json" TEXT NOT NULL DEFAULT '[]',
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "horizon_end" TIMESTAMP WITH TIME ZONE NOT NULL,
    "horizon_start" TIMESTAMP WITH TIME ZONE NOT NULL,
    "inputs_json" TEXT NOT NULL DEFAULT '[]',
    "objective_value" DOUBLE PRECISION NOT NULL,
    "produced_schedule_asset_id" TEXT,
    "produced_schedule_type" TEXT,
    "produced_schedule_version" INTEGER,
    "run_id" UUID NOT NULL,
    "solver_name" TEXT NOT NULL,
    "solver_runtime_seconds" DOUBLE PRECISION NOT NULL,
    "status" TEXT NOT NULL,
    "termination_reason" VARCHAR(256) NOT NULL,
    "time_step_seconds" DOUBLE PRECISION NOT NULL,
    "warnings_json" TEXT NOT NULL DEFAULT '[]',
    PRIMARY KEY ("run_id")
);

CREATE TABLE "schedules" (
    "asset_id" TEXT NOT NULL,
    "market_bid_area" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "version" INTEGER NOT NULL,
    PRIMARY KEY ("asset_id", "type")
);

CREATE TABLE "telemetry" (
    "active_power_kw" DOUBLE PRECISION NOT NULL,
    "asset_id" TEXT NOT NULL,
    "available" BOOLEAN NOT NULL,
    "data_quality_reason" TEXT NOT NULL,
    "data_quality_state" TEXT NOT NULL,
    "dc_current" DOUBLE PRECISION NOT NULL,
    "dc_voltage" DOUBLE PRECISION NOT NULL,
    "fault_status" TEXT NOT NULL,
    "id" BIGSERIAL,
    "reactive_power_kvar" DOUBLE PRECISION NOT NULL,
    "recorded_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "soc_percent" DOUBLE PRECISION NOT NULL,
    "soh_percent" DOUBLE PRECISION NOT NULL,
    "temperature_celsius" DOUBLE PRECISION NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE "optimization_objective_breakdowns" (
    "name" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    "run_id" UUID NOT NULL,
    "unit" TEXT NOT NULL,
    "value" DOUBLE PRECISION NOT NULL,
    CONSTRAINT "optimization_objective_breakdowns_run_id_fkey" FOREIGN KEY ("run_id") REFERENCES "optimization_runs" ("run_id") ON DELETE CASCADE,
    CONSTRAINT "optimization_objective_breakdowns_run_id_position_key" UNIQUE ("run_id", "position"),
    PRIMARY KEY ("run_id", "name")
);

CREATE TABLE "schedule_windows" (
    "asset_id" TEXT NOT NULL,
    "target_power_kw" DOUBLE PRECISION NOT NULL,
    "type" TEXT NOT NULL,
    "window_end" TIMESTAMP WITH TIME ZONE NOT NULL,
    "window_start" TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT "schedule_windows_asset_id_type_fkey" FOREIGN KEY ("asset_id", "type") REFERENCES "schedules" ("asset_id", "type") ON DELETE CASCADE,
    PRIMARY KEY ("asset_id", "type", "window_start")
);

CREATE INDEX "idx_audit_recorded_at" ON "audit_events" ("recorded_at" DESC);

CREATE INDEX "idx_commands_asset_issued_at" ON "commands" ("asset_id", "issued_at" DESC);

CREATE INDEX "idx_optimization_runs_asset_created_at" ON "optimization_runs" ("asset_id", "created_at");

CREATE INDEX "idx_telemetry_asset_recorded_at" ON "telemetry" ("asset_id", "recorded_at" DESC);
