#!/usr/bin/env bash
#
# ADR 0013 §5.3 — SUT smoke: prove the config-only path by running bess-ems
# (deploy/compose.sut.yml) against a SEPARATELY started field stack
# (deploy/compose.field.yml) coupled ONLY through the shared external Docker
# network `bess-sut`. This is the mechanical evidence behind
# docs/user/sut-field-endpoint.md: the same image, pointed at an "external"
# broker purely via environment, leaves the safety fallback and runs control
# cycles.
#
# Green criterion (plan-field-contract-sut-docs.md, sub-slice 2): the
# good-case line "Control cycle emitted command" (EventId 1701) appears
# within SUT_SMOKE_TIMEOUT seconds, and NO additional
# "Control cycle safe-stop" line appears during the SUT_SMOKE_WARMUP watch
# window afterwards. Only the safe-stop path carries a decision= field, so
# grepping for the emitted-command line is the only sound good-case signal.
#
# Environment:
#   SUT_SMOKE_TIMEOUT   — seconds to wait for the good-case signal (default 90)
#   SUT_SMOKE_WARMUP    — seconds to watch for late safe-stops (default 20)
#   SUT_SMOKE_DURATION  — seconds of generated scenario cadence (default 600)
#   DOCKER              — docker binary (default docker)
set -euo pipefail

DOCKER="${DOCKER:-docker}"
TIMEOUT="${SUT_SMOKE_TIMEOUT:-90}"
WARMUP="${SUT_SMOKE_WARMUP:-20}"
DURATION="${SUT_SMOKE_DURATION:-600}"
NETWORK="bess-sut"
SCENARIO="deploy/.sut-scenario.json"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

field() { "${DOCKER}" compose -f deploy/compose.field.yml -p bess-sut-field "$@"; }
sut()   { "${DOCKER}" compose -f deploy/compose.sut.yml   -p bess-sut-ems   "$@"; }

cleanup() {
  sut down -v --remove-orphans >/dev/null 2>&1 || true
  field down -v --remove-orphans >/dev/null 2>&1 || true
  "${DOCKER}" network rm "${NETWORK}" >/dev/null 2>&1 || true
  rm -f "${SCENARIO}"
}
trap cleanup EXIT

# The simulator walks a scenario's ticks once; bess-ems measures freshness at
# receive time (ADR 0013 §1). The integration fixture holds its first tick for
# 24h — a single retained publish, which correctly drives the SUT into
# safe-stop. Generate a constant-cadence scenario instead: 1s ticks, nominal
# values, long enough to outlive TIMEOUT + WARMUP.
echo "[sut-smoke] generating ${DURATION}s constant-cadence scenario at ${SCENARIO}"
python3 - "$DURATION" > "${SCENARIO}" <<'EOF'
import json
import sys

seconds = int(sys.argv[1])
base = {
    "soc_percent": 60.5, "soh_percent": 99.0,
    "active_power_kw": 0.0, "reactive_power_kvar": 0.0,
    "dc_voltage": 800.0, "dc_current": 0.0,
    "temperature_celsius": 22.0, "available": True, "fault_status": "ok",
}
print(json.dumps({
    "id": "sut-smoke-cadence",
    "name": "SUT smoke - constant cadence",
    "description": "Generated by scripts/sut-smoke.sh: nominal snapshot every second so the SUT never ages out (ADR 0013 cadence rule).",
    "asset": {
        "asset_id": "single-bess-1", "capacity_kwh": 100,
        "max_charge_power_kw": 50, "max_discharge_power_kw": 50,
        "min_soc_percent": 10, "max_soc_percent": 90,
        "charge_efficiency": 0.95, "discharge_efficiency": 0.95,
        "max_ramp_kw_per_second": 25,
        "min_operating_temperature_celsius": -20,
        "max_operating_temperature_celsius": 55,
    },
    "telemetry": [dict(base, offset_millis=i * 1000) for i in range(seconds)],
}, indent=2))
EOF

echo "[sut-smoke] creating shared external network '${NETWORK}'"
"${DOCKER}" network inspect "${NETWORK}" >/dev/null 2>&1 \
  || "${DOCKER}" network create "${NETWORK}" >/dev/null

echo "[sut-smoke] starting the stand-in field stack (separate compose project)"
field up -d --wait --wait-timeout 60

echo "[sut-smoke] starting the SUT variant against it (config-only coupling)"
sut up -d --wait --wait-timeout 60

echo "[sut-smoke] waiting up to ${TIMEOUT}s for 'Control cycle emitted command'"
deadline=$(( SECONDS + TIMEOUT ))
until sut logs bess-ems 2>/dev/null | grep -q "Control cycle emitted command"; do
  if (( SECONDS >= deadline )); then
    echo "[sut-smoke] FAILED — no good-case signal within ${TIMEOUT}s; last log lines:" >&2
    sut logs --tail 40 bess-ems >&2 || true
    exit 1
  fi
  sleep 2
done
echo "[sut-smoke] good-case signal seen; watching ${WARMUP}s for late safe-stops"

safe_stop_count() {
  sut logs bess-ems 2>/dev/null | grep -c "Control cycle safe-stop" || true
}
before="$(safe_stop_count)"
sleep "${WARMUP}"
after="$(safe_stop_count)"
if (( after > before )); then
  echo "[sut-smoke] FAILED — ${after} safe-stop lines after warmup (was ${before}); the loop fell back:" >&2
  sut logs bess-ems 2>/dev/null | grep "Control cycle safe-stop" | tail -5 >&2
  exit 1
fi

echo "[sut-smoke] OK — control loop runs against the external endpoint (config-only), no safe-stop after warmup"
