apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bess-ems.secretName" . }}
  labels:
    {{- include "bess-ems.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.apiToken.token | quote }}
  {{- if .Values.postgres.enabled }}
  postgres-password: {{ .Values.postgres.password | quote }}
  persistence-connection-string: {{ include "bess-ems.postgresConnectionString" . | quote }}
  {{- end }}
