<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BatteryEms.Adapters.Mqtt</RootNamespace>
    <AssemblyName>BatteryEms.Adapters.Mqtt</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\hexagon\BatteryEms.Application\BatteryEms.Application.csproj" />
    <ProjectReference Include="..\..\..\hexagon\BatteryEms.Domain\BatteryEms.Domain.csproj" />
  </ItemGroup>

</Project>
