<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>BatteryEms.OpcUa.IntegrationTests</RootNamespace>
    <AssemblyName>BatteryEms.OpcUa.IntegrationTests</AssemblyName>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua.Server" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\hexagon\BatteryEms.Domain\BatteryEms.Domain.csproj" />
    <ProjectReference Include="..\..\..\src\hexagon\BatteryEms.Application\BatteryEms.Application.csproj" />
    <ProjectReference Include="..\..\..\src\adapters\driven\BatteryEms.Adapters.OpcUa\BatteryEms.Adapters.OpcUa.csproj" />
    <ProjectReference Include="..\..\..\src\infrastructure\BatteryEms.Infrastructure\BatteryEms.Infrastructure.csproj" />
  </ItemGroup>

</Project>
